export const FILTER = {
    ALL: "ALL",
    REACT: "REACT",
    REDUX: "REDUX"
}

export const BUY_ITEM = "BUY_ITEM";
export const WISH_ADD_ITEM = "WISH_ADD_ITEM";
export const WISH_REMOVE_ITEM = 'WISH_REMOVE_ITEM';
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SHOW_MODAL = 'CART_SHOW_MODAL';
export const REMOVE_ITEM = "REMOVE_ITEM";
export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_RECEIVE = "FETCH_DATA_RECEIVE";
export const FETCH_ITEM_DATA_RECEIVE = 'FETCH_ITEM_DATA_RECEIVE';
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
export const ITEM_SELECTED_HANDLER = "ITEM_SELECTED_HANDLER";
export const MODAL_CLOSE_HANDLER = 'MODAL_CLOSE_HANDLER';
export const MODAL_SHOW_INFO = 'MODAL_SHOW_INFO';
export const MODAL_SHOW_CART = 'MODAL_SHOW_CART';
export const MODAL_SHOW_WISH = 'MODAL_SHOW_CART';

